<?php
/**
  * AUTOMNE CONFIGURATION FILE
  * This file is generated by Automne installation process (install.php file).
  * If you need to modify any configuration constants of files
  * cms_rc.php, cms_rc_admin.php or cms_rc_frontend.php
  * simply define the constant and it's new value in this file
  *
  * @package Automne
  * @subpackage config
  * @author Sebastien Pauchet <sebastien.pauchet@ws-interactive.fr>
  */

define("APPLICATION_DB_HOST", "DB_HOST");
define("APPLICATION_DB_NAME", "DB_NAME");
define("APPLICATION_DB_USER", "DB_USER");
define("APPLICATION_DB_PASSWORD", "DB_PASSWORD");

define("FILES_CHMOD", "0644");
define("DIRS_CHMOD", "0755");

define("APPLICATION_XHTML_DTD", "<!DOCTYPE html>");
?>